### ISSUE TITLE
Add support for agent forwarding

### ISSUE THREAD

**Issue by barryvan** [cuviper/ssh-pageant#32]
Pageant, when used with PuTTY, allows agent forwarding (see http://the.earth.li/~sgtatham/putty/0.58/htmldoc/Chapter9.html#pageant-forward). If this were possible via `ssh-pageant`, it would make it much easier to work via remote servers. Is this perhaps already an option that I'm just missing?

**Comment by cuviper** [comment]
As far as I know, this is entirely up to each ssh client, not the agent
itself.  With the normal ssh command, you can either use the `-A` flag or
set `ForwardAgent yes` in your config.

Here is github's help for example:
https://developer.github.com/guides/using-ssh-agent-forwarding/

**Comment by barryvan** [comment]
Thanks @cuviper -- I learnt something new today! I appreciate the quick and helpful response.
