### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by castanley** [cuviper/ssh-pageant#33]
I am using Windows 8.1 and am receiving the following error:

ssh-pageant.exe: error while loading shared libraries: msys-1.0.dll

Any ideas?

**Comment by cuviper** [comment]
If you're using the prebuilt MSYS binary, note that only works with the
original MSYS, not MSYS2 or Cygwin.  There are Cygwin downloads available
too, but for MSYS2 you'll have to build from source.  I'll add it to the
prebuilt list next time I do a release.

**Comment by castanley** [comment]
Awesome, thanks for the information. I will build it from source and see if this remedies the problem!
