### ISSUE TITLE
How to handle "ssh-pageant: connect: Connection refused"?

### ISSUE THREAD

**Issue by tiesmaster** [cuviper/ssh-pageant#36]
I've configured my setup as described, however, I always get "ssh-pageant: connect: Connection refused" when I've rebooted Windows. To fix that, I need to remove the socket at startup of Windows.

Any ideas? I've fixed it now like [this](https://github.com/tiesmaster/dotfiles/commit/9663b8a5a9244bc0e21e01cfee16d67280050f85), but that's really a hack...

**Comment by cuviper** [comment]
Is this with MSYS?  If so, it's probably #31, and you'll probably be better off just using separate generated sockets for each instance.  Simply `eval $(ssh-pageant)` without `-r` or `-a`, then configure a logout trap for `ssh-pageant -k`.

**Comment by tiesmaster** [comment]
Yeah, indeed! I did check the issues, but didn't saw that one :(

It's a pity, it cannot be reused. I was just going to change it to do this, and I noticed that I have already quite a number of "zombies" running :(

Do you know if this is fixed in MSYS2?

![image](https://cloud.githubusercontent.com/assets/460904/8960816/17458a1c-3612-11e5-82bc-9ab9c9b8da71.png)

**Comment by cuviper** [comment]
Yes, MSYS2 should be ok.  Cygwin fixed this quite a long time ago, but MSYS is an even older fork, and they don't really update the runtime.  I believe MSYS2 stays in sync with current Cygwin.

Perhaps I should add a "force" option to clobber unresponsive sockets even if they don't look like a socket (which is where S_IFSOCK comes in).

I'd call your "zombies" more like "orphans" -- they're still alive and working, just unowned.  You can arrange to clean up with `trap logout HUP` in `.bash_profile` (assuming that's where you started it) and `ssh-pageant -k` in `.bash_logout`.  Tweak as needed if you have a different shell.  This is how I use it in Cygwin, and I don't get orphans, but it's possible MSYS could still be deficient here somehow.

**Comment by tiesmaster** [comment]
Indeed, they're not really zombies, as in the OS terminology ;) I found out that was more related to not closing ssh-pageant after closing a shell, in general. I've added a bash_logout, and that works great :+1:
