### ISSUE TITLE
"Connection refused" on starting MSYS bash - old sockets not being deleted?

### ISSUE THREAD

**Issue by stephenfrancis** [cuviper/ssh-pageant#37]
Am using Pageant (0.66) with Git (1.9.5) on Windows 7 Pro (SP1).
I want to be able to use the Git Bash shell (MSYS) to ssh onto various Linux servers.
I downloaded and followed the instructions, and, first time, everything worked fine.

Next day, however, on starting bash, I was seeing a "connection refused" message at the start of the shell, and was being prompted for a password on sshing onto the servers.

I notice that /tmp/.ssh-pageant-[username] isn't deleted - could this be the problem? If I delete it and restart bash then everything works fine. What is supposed to delete this when I restart Windows (and hence Pageant)?

I also noticed that I was getting other files in /tmp/ssh/...

I guess that just putting the following into .bashrc would be a solution?
eval $(/usr/bin/ssh-pageant)
Seems to work...

All advice much appreciated.

**Comment by cuviper** [comment]
Yes, there was a problem with socket detection filed as #31, which is hopefully fixed now in master.  If you're able to build your own ssh-pageant with MSYS build tools, it would be nice to get confirmation.  I need to put out a new release -- I've just been procrastinating some documentation tweaks I want to make. :)

Starting separate instances with their own automatic tmp paths is perfectly fine.  You might want to kill them in a bash logout script though, so you don't accumulate a bunch of disconnected processes.

**Comment by cuviper** [comment]
In absence of further feedback, I'm closing as a dupe.  Feel free to re-open with more info if needed.
