### ISSUE TITLE
Windows-Git support

### ISSUE THREAD

**Issue by klaernie** [cuviper/ssh-pageant#41]
Could you try to make a Msys 64bit complilate too? I think for the pure git bash users ssh-pageant is very important, as SSH keys are so essential to git's operation. But many environments already have putty and pagent running, or specific pageant replacements that implement the protocol.

So I would really like to see support for such a popular package, maybe even the integration the other way round would be better, by integrating ssh-pageant into windows-git.

**Comment by maehne** [comment]
ssh-pageant is already available in MSYS2:

https://github.com/Alexpux/MSYS2-packages/tree/master/ssh-pageant-git

Since Git for Windows is based on MSYS2, it is quite easy to integrate Git for Windows into a regular MSYS2 installation:

https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper

Then, you can use ssh-pageant, as wished to fetch your SSH key from Pageant and use them together with Git. I am using this setup already for some time on my Windows machine. It works well.

**Comment by cuviper** [comment]
I intend to build an MSYS2 binary next time I make a release.  That's long overdue, I admit.  We can leave this bug open until then to keep nagging me. :)

Running a full installation MSYS2 (or even Cygwin) as @maehne suggests is a good option.  Then you'll get pre-packaged versions of many, many other programs too.  Or you could just try stealing MSYS2's specific package for ssh-pageant and drop that into your windows-git installation. http://repo.msys2.org/msys/

I'd be happy to see windows-git include ssh-pageant themselves.  They're totally free to do so.

**Comment by klaernie** [comment]
I'm perfectly happy to nag them!

**Comment by landstander668** [comment]
For what it's worth, I've added instructions explaining [how to manually configure ssh-pageant](https://github.com/git-for-windows/git/wiki/OpenSSH-Integration-with-Pageant) to the Git for Windows Wiki. While that's less desirable than proper integration, naturally, it's pretty easy to do and works beautifully.

**Comment by landstander668** [comment]
I've created a (surprisingly simple) [pull request](https://github.com/git-for-windows/build-extra/pull/109) against the [git-for-windows/build-extra repository](https://github.com/git-for-windows/build-extra), which integrates _ssh-pageant_ into the Git for Windows build. It's been working flawlessly during all of my testing, so I've indicated that it's (believed to be) complete and just needs to be merged. Hopefully they'll agree. :)

**Comment by cuviper** [comment]
Great!  I thought it might be easy, thanks to @sschuberth packaging it in MSYS2 already.

**Comment by landstander668** [comment]
Absolutely! There's no doubt this was made *much* simpler, thanx to the foundation @sschuberth had already laid down! :+1:

**Comment by sschuberth** [comment]
Thanks for the credits guys! :-)

**Comment by landstander668** [comment]
@cuviper Ssh-pageant integration has been merged into Git for Windows ([primary](https://github.com/git-for-windows/build-extra/pull/109) and [helper](https://github.com/git-for-windows/MINGW-packages/pull/17) pull requests), and should be included in the next release. So it's probably OK to close this issue now. :)

**Comment by cuviper** [comment]
Sure. Thanks again!
