### ISSUE TITLE
Add support for Microsoft's new "Linux" subsystem

### ISSUE THREAD

**Issue by cuviper** [cuviper/ssh-pageant#43]
It seems that Microsoft is reviving something like Interix/SUA/SFU of old.  If programs in this environment can simultaneously work with `AF_UNIX` sockets and Windows APIs like `SendMessage`, then it should be possible to port ssh-pageant.

http://www.winbeta.org/news/windows-10-build-14251-linux-subsystem-files-mean
http://www.zdnet.com/article/microsoft-and-canonical-partner-to-bring-ubuntu-to-windows-10/

**Comment by cuviper** [comment]
From what I'm reading, it sounds more like the reverse of WINE, and I suspect that environment won't be able to use Windows APIs.  We shall see...

**Comment by nistvan86** [comment]
Yes, you're right. Just tried to compile ssh-pageant and it can't find the Windows headers.
![ssh-pageant](http://i.imgur.com/F34bWXo.png)

**Comment by cuviper** [comment]
Thanks for looking.  I just tried it myself too, and that subsystem is *really* isolated.  It can't even see that native-Windows processes exist at all -- which I suppose makes sense, because otherwise Linux apps might try to interact in unsupported ways like sending signals.

Perhaps if they get an ssh server in there, you could log in that way and use normal agent forwarding, but I don't think there's any way for ssh-pageant to directly support WSL.
