### ISSUE TITLE
Add support for ubuntu on windows

### ISSUE THREAD

**Issue by StingRayZA** [cuviper/ssh-pageant#44]
'[Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about)' is a new thing on Windows 10. I'd love to be able to let that speak to my pageant instance - the same way my ssh-pageant does under cygwin.

I took a brief stab at getting it to compile on my environment. No go. But then I'm not exactly a multiplatform c pro.

**Comment by cuviper** [comment]
See #43 -- unfortunately, I don't think this is possible.

**Comment by StingRayZA** [comment]
My bad for the dup. I checked open tickets, didn't think to check closed.

sad about the answer, but oh well - was worth a try.

Thanks

**Comment by cuviper** [comment]
No worries, it sure would be nice if it could work!
