### ISSUE TITLE
error while loading shared libraries: ?

### ISSUE THREAD

**Issue by ivangretsky** [cuviper/ssh-pageant#45]
Good day!

I am trying to make my gitbash on Windows 10 work with Pegeant. I am following instructions, but get this weird error on shell strtup:

`bin/ssh-pageant.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory`

Yes, with the question mark. What could this be?

**Comment by cuviper** [comment]
I'm not sure, but my best guess is that you need to use binaries for msys2, either 32-bit or 64-bit depending on your installation, which I haven't published.  I keep saying I should do a new release, but I need to do some doc work and haven't gotten around to it.

If by gitbash you mean a [git-for-windows](https://github.com/git-for-windows/) shell, then I think that work for integration was already done by #41.  As I understand it, `ssh-pageant` should already be included in their latest releases, and you can find instructions here: https://github.com/git-for-windows/git/wiki/OpenSSH-Integration-with-Pageant

**Comment by ivangretsky** [comment]
Thank you very much. It was indeed fit-for-windows. I had ro update my installation and modify the .bash_profile with the [code provided](https://github.com/git-for-windows/git/wiki/OpenSSH-Integration-with-Pageant#starting-ssh-pageant-manually-from-git-bash). Now running `ssh-add -l` shows the keys loaded in pegeant. 

Thank you again for you great code and fast answer!
