### ISSUE TITLE
Does this work with Windows Subsystem for Linux (WSL) ?

### ISSUE THREAD

**Issue by meffect** [cuviper/ssh-pageant#47]
Does this work with Windows Subsystem for Linux (WSL) ?

**Comment by cuviper** [comment]
I investigated this in #43.  I don't think it's possible to use ssh-pageant, because the WSL environment doesn't have access to the Windows APIs needed to talk to Pageant.

**Comment by meffect** [comment]
oh ok tyvm!

**Comment by meffect** [comment]
Does this insider [build 14951](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-14951) sound like it will fix the problem? There is also a [Channel 9](https://blogs.msdn.microsoft.com/wsl/2016/10/19/windows-and-ubuntu-interoperability/) video about it

**Comment by cuviper** [comment]
Hmm, *maybe*.  It's a good start if you can now see native processes, but ssh-pageant still needs access itself to both `AF_UNIX` sockets and Windows APIs.  A Linux binary would never have the latter, and so I'd expect the subsystems are still isolated within a given process. (unlike Cygwin et al.)

Maybe it could be done with multiple processes.  Say, a `ssh-pageant-win` that talks to Pageant and translates on a pipe or stdin/stdout, and then a `ssh-pageant-lin` which routes that to the `AF_UNIX` socket that Linux programs want for the agent.  I think you could probably even handle the second part with `socat`.  I'm not sure how this would handle multiple connections though.

That's a pretty significant departure though.  Basically all of main.c would be rewritten to be a native Windows process, and only winpgntc.c would be the same, which is already basically just copied from PuTTY.

**Comment by vuori** [comment]
A small advertisement: I have implemented this using the new Win32 interop facilities shipped with Creators Update as a modification of `ssh-pageant`. If the OP is still interested (and running CU or newer), my version is now available at https://github.com/vuori/weasel-pageant

**Comment by cuviper** [comment]
@vuori I see you implemented the pipe idea, nice!  I'd be happy to list your project in the Links section of my readme, if you'd like to send a PR.

**Comment by endosynth** [comment]
👍
