### ISSUE TITLE
1.4 always exits with 127

### ISSUE THREAD

**Issue by Galen007** [cuviper/ssh-pageant#48]
I've learned 127 means wrong architecture, but 32 and 64-bit cygwin version are exiting with exitcode 127.

$ uname -a
CYGWIN_NT-6.1 xxxxxxx 1.7.28(0.271/5/3) 2014-02-09 21:06 x86_64 Cygwin

I tried 64 bit version of ssh-pageant 1.3 and it works fine.

**Comment by cuviper** [comment]
> 1.7.28(0.271/5/3) 2014-02-09

That's quite old -- is it possible for you to update Cygwin?

I think I've seen this before, that the 1.4 binaries got linked with symbols from a newer Cygwin, which won't resolve on something older.  You could probably rebuild ssh-pageant on your version of Cygwin and it will be fine, but generally I'd suggest you update everything.

And FWIW, the current Cygwin repositories also include an ssh-pageant package.

**Comment by Galen007** [comment]
ok, i'll try to get a newer cygwin version :)
