### ISSUE TITLE
Question: Is it possible to enable agent forwarding with ssh-pageant when using cygwin?

### ISSUE THREAD

**Issue by shreyasz** [cuviper/ssh-pageant#49]
Hello, the reason I am using cygwin is so I can ssh into my server from my work windows machine. To do that I must use a bastion host. This means I must use agent forwarding.

This works when I use PuTTY, with "Allow agent forwarding" enabled in the Auth properties. I see this working when I type echo $SSH_AUTH_SOCK in my bastion server.

This _does not work_ when I am using ssh-pageant in cygwin.

Help/suggestions??

**Comment by cuviper** [comment]
Forwarding is a question of the client.  Assuming you're in a shell with the agent configured properly, then `ssh -A` should forward it.

**Comment by shreyasz** [comment]
@cuviper: That worked perfectly! Thanks for the quick reply!!
