### ISSUE TITLE
"error while loading shared libraries" in cygwin mintty

### ISSUE THREAD

**Issue by willemdh** [cuviper/ssh-pageant#51]
Hello,

I seem to have issues getting this to work when used in a task I'm trying to create for Conemu. My private key is loaded in Pageant.

So I try to start an ssh session like this:

`%userprofile%\.babun\cygwin\bin\mintty.exe /bin/bash -c '/usr/bin/uname -a ; eval $(/usr/sbin/ssh-pageant) ; /usr/bin/ssh user@b01.outsideit.net'`

But the results is:

```
CYGWIN_NT-10.0-WOW FIREBASE 1.7.35(0.287/5/3) 2015-03-04 12:07 i686 Cygwin
/usr/sbin/ssh-pageant.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
Enter passphrase for key '/home/user/.ssh/id_rsa':
```

Any advice to get this working is much appreciated. I have tried with both the 32 bit as the 64 bit ssh-pageant.

Willem

**Comment by willemdh** [comment]
The weird thing is that when I open mintty and then execute:

`/bin/bash -c '/usr/bin/uname -a ; eval $(/usr/sbin/ssh-pageant) ; /usr/bin/ssh user@b01.outsideit.net'`

it actually works fine... What could be different between running this manually and running it as a parameter?

**Comment by cuviper** [comment]
I definitely looks like you need the 32-bit version.  But Cygwin does have ssh-pageant available as a normal package now, have you tried that?  It will be `/usr/bin/ssh-pageant`, not `sbin`.

> `1.7.35(0.287/5/3) 2015-03-04`

That's really old - they're up to `2.9.0(0.318/5/3) 2017-09-12` now.  Can you update your installation?

> The weird thing is that when I open mintty and then execute: [...] it actually works fine...

My guess is that executing from the mintty argument string is not setting up Cygwin in the `PATH`, where as it does when you open to a shell first.  Windows looks in the executable's directory for libraries regardless of `PATH`, so your commands in `/usr/bin/` would still find `cygwin1.dll` and all, but the `/usr/sbin/` command would have no such luck.

**Comment by willemdh** [comment]
@cuviper Thanks for the super fast answer. 

```
babun update
Executing babun update
  upstream  [release]
  installed [1.2.0]
  newest    [1.2.0]
Babun is up to date
Checking Cygwin version:
  installed [1.7.35]
  newest    [1.7.35]
Cygwin is up to date
```
Weird 1.7.35 seems to be the latest cygwin version.. Found this Github issue https://github.com/babun/babun/issues/516

Tried running update.bat but I get:
```
./update.bat
[babun] Wget not found. Babun installation seems to be corrupted.
Press any key to continue . . .

 wille@FIREBASE%
 wille@FIREBASE% wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

But as all the above didn't really help me, I tried copying the ssh-pageant.exe from /usr/sbin to /usr/bin and it works as expected now.

Tx!
