### ISSUE TITLE
Invalid version distributed through Cygwin package repository

### ISSUE THREAD

**Issue by ferenczy** [cuviper/ssh-pageant#56]
I noticed that I haven't been using the most recent version of `ssh-pagent` so I wanted to update it.

I have been using the version 1.3, the most recent release on this site is 1.4.

I'm using Cygwin, so I have executed `setup.exe` just to find out that according to the installer, I already have the most recent version. It's even marked as 1.4-1 in the installer but `ssh-pageant --version` revealed it's in fact 1.3. Also, the file size didn't match and both versions were binary different.

In the end, I simply took the most recent version from this repository.

**Comment by cuviper** [comment]
> but `ssh-pageant --version` revealed it's in fact 1.3.

Are you sure you ran the program in `/usr/bin/`?  What does `which ssh-pageant` say?

**Comment by themiwi** [comment]
Hi, I am the maintainer of the Cygwin package. I'll check this tomorrow.

**Comment by themiwi** [comment]
Sorry for the delay. Below my diagnosis; everything appears to be fine for me.

```bash
$ which ssh-pageant
/usr/bin/ssh-pageant
$ cygcheck -c ssh-pageant
Cygwin Package Information
Package              Version        Status
ssh-pageant          1.4-1          OK
$ ssh-pageant --version
ssh-pageant 1.4
Copyright (C) 2009-2014  Josh Stone
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Seems to be fine for me.

**Comment by cuviper** [comment]
Thanks for confirming!

@ferenczy, feel free to reopen the issue if you have more details.
