### ISSUE TITLE
Can I use this with Git Bash/mintty/MINGW64?

### ISSUE THREAD

**Issue by Bilge** [cuviper/ssh-pageant#60]
I use [Git Bash](https://gitforwindows.org/) client but it seems none of the distributed executables work with it. 

I get one of the following two errors depending on the specific executable:

> ssh-pageant.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

>ssh-pageant.exe: error while loading shared libraries: cygwin1.dll: cannot open shared object file: No such file or directory

Is there a solution for me?

**Comment by cuviper** [comment]
My understanding is that Git for Windows already distributes their own build of ssh-pageant, so ideally you should use that. See the original [issue](https://github.com/git-for-windows/git/issues/683) and their [wiki](https://github.com/git-for-windows/git/wiki/OpenSSH-Integration-with-Pageant).

**Comment by Bilge** [comment]
Thanks! That's awesome. Thanks for helping me out, and so quickly, too! 👍
